set ruler
set number  
set expandtab   
set autoindent  
set smartindent    
set cindent  
set tabstop=4    
set softtabstop=4   
set shiftwidth=4   
set smarttab   
set nocompatible  
set history=1000  
set fenc=utf-8  
set pastetoggle=<F11>  
set showmatch  
set matchtime=5  
set hlsearch   
set incsearch  
filetype on  
colorscheme evening  
syntax enable    
syntax on  
